backend:
  name: github
  repo: NUVARY/NEXATA-INSIGHT-MEDIA-STUDIO
  branch: NUVARY-(B)
  site_domain: stellar-frangollo-e1f250.netlify.app

media_folder: "IMAGENES/Portada de blog"
public_folder: "/NEXATA-INSIGHT-MEDIA-STUDIO/IMAGENES/Portada%20de%20blog"

collections:

  - name: "articulos"
    label: "Artículos"
    label_singular: "Artículo"

    folder: "_posts"

    create: true

    extension: "md"

    format: "frontmatter"

    slug: "{{slug}}"

    fields:

      - label: "Título"
        name: "title"
        widget: "string"
        hint: "Título principal del artículo."

      - label: "Descripción"
        name: "description"
        widget: "text"
        hint: "Descripción breve del artículo."

      - label: "Categoría"
        name: "category"
        widget: "select"
        options:
          - "Tecnología"
          - "Juegos"
          - "Marketing y motivación"
          - "Finanzas personales"
          - "Salud"
          - "Curiosidades del mundo"
          - "Todo y más"

      - label: "Imagen destacada"
        name: "image"
        widget: "image"

      - label: "Fecha de publicación"
        name: "date"
        widget: "datetime"

      - label: "Contenido"
        name: "body"
        widget: "markdown"
